REQ = "req"
RES = "res"
NTF = "ntf"

ENUM = "enum"
MESSAGE = "message"

NAME = "name"
USER_DEF_TYPE = "user_def_type"
SINGLE_TYPE = "single_type"
UE_TYPE = "type"
REPEATED = "repeated"
COMMENT = "comment"
PB_TYPE = "pb_type"
VALUE = "value"
